### ISSUE TITLE
Drop Python 2.7

### ISSUE THREAD

**Issue by PMeira** [dss-extensions/dss_python#19]
Since most scientific Python modules will drop Python 2.7 in jan/2019, general Python 2.7 usage should start dropping. This is reminder to watch the number of downloads in the following months to decide when to drop Python 2.7 in DSS Python. 

~~Tentative date: may/2019.~~

**Comment by PMeira** [comment]
The number of downloads for Python 2.7 is getting low. In 2019, most downloads were from 3.6 and 3.7, while 2.7 had a lower number than 3.5. Soon, it should be dropped, at least for the master branch.

**Comment by PMeira** [comment]
@kdheepak Any insight on this, especially about ODD.py? 

Right now, from [pypistats](https://pypistats.org/packages/opendssdirect-py), it seems most users are using Python 3.6 and 3.7, while 2.7, 3.5 and 3.8 have about the small same share of users. Of course Python 3.8 should grow as time goes.

**Comment by kdheepak** [comment]
I think with the rewrite we can and should drop support for Py27. It'll allow us to use some nicer Python features and make it easier to maintain as well. I know there some users out there that are using Python 2.7 interfaces in some proprietary commercial software and interfacing with OpenDSS in the same process, but they will have to make do with the older versions of these packages.

**Comment by PMeira** [comment]
Done in my local repo. I'll merge as soon as I finish some other changes for 0.11.x.
