### ISSUE TITLE
macOS M1 arm64

### ISSUE THREAD

**Issue by chhokrad** [dss-extensions/dss_python#41]
I am not able to install the dss_python using pip. 

System:
MacBook Pro 
Apple M1 Max
macOS Monterey 12.1
pip 22.0.4
Python 3.10.2

Error:
<img width="678" alt="Screen Shot 2022-03-07 at 3 15 09 PM" src="https://user-images.githubusercontent.com/9986578/157110985-0e21ef11-77dc-40ec-a3b4-ae3a82cb4fe1.png">

<img width="745" alt="Screen Shot 2022-03-07 at 3 16 02 PM" src="https://user-images.githubusercontent.com/9986578/157111087-e03ef801-422e-4eba-90fa-08af1cafda2b.png">

**Comment by PMeira** [comment]
M1 ARM is not supported yet.
We can build for ARM64 Linux already, but we don't have any machines or CI with M1 support, AFAICT.

**Comment by PMeira** [comment]
I just adjusted the build scripts for DSS C-API to include aarch on macOS in the next release PR at https://github.com/dss-extensions/dss_capi/pull/109

I imagine building the Python wheel won't be much harder, but still there is the lack of testing. We could release it anyway and just add a warning to the release notes, but people rarely read those.

**Comment by PMeira** [comment]
I added a cross-compiled wheel:

```shell
pip install dss-python==0.12.0b2
```

Untested, but should work.

**Comment by PMeira** [comment]
The build steps are now integrated in the workflow for GitHub Actions, so wheels for macOS ARM64 are prepared with the rest.

**Comment by charraig** [comment]
Hi @PMeira, thanks for working on the M1 architecture. I just tested with macOS 12.0.1 on M1 w/ Python 3.9.10 virtualenv, but received an `ImportError:

```
pip install dss-python==0.12.0b3
python
>>> import dss
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.pyenv/versions/testodd/lib/python3.9/site-packages/dss/__init__.py", line 5, in <module>
    from .v7 import *
  File "~/.pyenv/versions/testodd/lib/python3.9/site-packages/dss/v7.py", line 9, in <module>
    from ._dss_capi import ffi, lib
ImportError: dlopen(~/.pyenv/versions/testodd/lib/python3.9/site-packages/dss/_dss_capi.abi3.so, 0x0002): tried: '~/.pyenv/versions/testodd/lib/python3.9/site-packages/dss/_dss_capi.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/_dss_capi.abi3.so' (no such file), '/usr/lib/_dss_capi.abi3.so' (no such file), '~/.pyenv/versions/3.9.10/envs/testodd/lib/python3.9/site-packages/dss/_dss_capi.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/_dss_capi.abi3.so' (no such file), '/usr/lib/_dss_capi.abi3.so' (no such file)
```

**Comment by PMeira** [comment]
@charraig Thanks for testing it! Please retry with `pip install dss-python==0.12.0b4`. A compiler flag was missing in the previous one, so the output libs resulted in mixed architectures.

**Comment by charraig** [comment]
@PMeira Thanks! I tested the new version and it worked perfectly.
